### ISSUE TITLE
Postgresql is not set up correctly.

### ISSUE THREAD

**Issue by tamouse** [jhsu802701/vagrant_debian_wheezy_rvm#1]
Getting these errors when trying to create a postgresql database with a standard install:

```
PG::InvalidParameterValue: ERROR:  encoding UTF8 does not match locale en_US
DETAIL:  The chosen LC_CTYPE setting requires encoding LATIN1.
: CREATE DATABASE "my_test_app_development" ENCODING = 'unicode'
```

This is due to how the postgres `initdb` script was run during installation.  See <http://stackoverflow.com/questions/26393572/rails-setup-with-vagrant-using-jumpstartlabs> for an explanation.

**Comment by jhsu802701** [comment]
Corrected in version 2015_02_03
