### ISSUE TITLE
cannot test RVM in step 5

### ISSUE THREAD

**Issue by SHoar** [jhsu802701/vagrant_debian_wheezy_rvm#2]
from OS X 10.10.2/ vagrant debian/wheezy, the response I get from cd /home/vagrant/shared is permission denied.

able to to cd /home/vagrant/ but not shared/

tried with sudo, and it said 'sudo: cd: command not found'

**Comment by jhsu802701** [comment]
Everything works for me in OS X 10.9.5.  

From /home/vagrant, what do you see when you enter "ls -l"?  I get:
total 4
drwxr-xr-x 1 vagrant vagrant 510 Feb  9 00:01 shared
-rw-r--r-- 1 vagrant vagrant  15 Feb  3 01:45 timestamp.txt

What are the contents of the timestamp.txt file?  When I enter "cat timestamp.txt", I get:
2015_0203_0145

**Comment by SHoar** [comment]
vagrant package/box is now working! Very nice!

vagrant@vagrant-rvm:~$ ls -l
total 4
drwxr-xr-x 1 vagrant vagrant 442 Feb 11 20:22 shared
-rw-r--r-- 1 vagrant vagrant  15 Feb  3 01:45 timestamp.txt
